### ISSUE TITLE
XNGAPIClient not available

### ISSUE THREAD

**Issue by alex-chelombitko** [xing/XNGAPIClientTester#4]
Hey,
we are using XNGAPIClient in our iOS app, today we've noticed that repository https://github.com/xing/XNGAPIClient is not accessible any more. Any news when it will be accessible again? 
Thanks

**Comment by stefanmunz** [comment]
Hey Alex,
thanks for reaching out! Our XNGAPIClient saw very little love in the last years. We recently discussed this internally and came to the conclusion that this will not change. As a consequence we decided to delete the repository to make this clear to everybody. I am happy if it still brings value to you and your company. My recommendation is to internalize it, as there will be no further updates from our side.

**Comment by o15a3d4l11s2** [comment]
Well, not maintaining it is completely understandable, but was it necessary to delete it completely? We just recently realised ourselves that the library is no more. Would be good to deprecate it but leave it to exist.
